language: python
python:
  - 2.7
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap-buildout.py --setuptools-version=8.3 -c travis.cfg
  - bin/buildout --plone.recipe.plone=4.3.6 -Nc travis.cfg
script:
  - bin/code-analysis
  - bin/test
  - bin/createcoverage
after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    - tisto@plone.org
