language: python
python:
  - 2.7
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py -c travis.cfg --setuptools-version=8.3
  - bin/buildout -Nc travis.cfg
script:
  - bin/test
  - bin/createcoverage
after_success:
  - pip install coveralls
  - coveralls
notifications:
  email:
    - tisto@plone.org
